# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/crm_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Porta
server.port=8080

# JWT — chave fixa (não regenerar a cada restart). Em produção use variável de ambiente.
jwt.secret=inGA5CGFzv2MecMHVfrMuI2jGwXdRfn2zGg4Aykp6asWU03uJ1FaEEMrw1CDp+m/
